[package]
name = "bats"
kind = "bin"

[dependencies]
"argparse" = ""
"arith" = ""
"array" = ""
"builder" = ""
"env" = ""
"file" = ""
"list" = ""
"path" = ""
"process" = ""
"result" = ""
"sha256" = ""
"str" = ""
"toml" = ""
